### ISSUE TITLE
walle-cli对于双引号路径解析的bug

### ISSUE THREAD

**Issue by k1988** [Meituan-Dianping/walle#107]
## bug应用场景
我使用一个批处理文件来对一个apk进行处理，输出到apk所在目录，就写了以下代码。
```
set src=%1%
set dest=%~dp1%
java -jar walle-cli-all.jar batch -f channel.txt  "%src%" "%dest%"
pause
```

## bug表现
其中第三行中，"%dest%"在windows上会输出路径`"D:\git\walle\walle-cli\"`，这种路径会被项目中使用的jcommander解析为`D:\git\walle\walle-cli“`。于是在输出apk时就提示
```
java.io.IOException: 文件名、目录名或卷标语法不正确。
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(Unknown Source)
        at java.io.File.getCanonicalPath(Unknown Source)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1076)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1040)
        at com.meituan.android.walle.commands.BatchCommand.generateChannelApk(BatchCommand.java:79)
        at com.meituan.android.walle.commands.BatchCommand.parse(BatchCommand.java:64)
        at com.meituan.android.walle.Main.main(Main.java:51)
```

## 其它
当然我知道这个锅应该jcommander来背，它对于双引号包括的斜杠结尾的路径处理的不对，但是还是想问问不改他们代码的情况下你们有什么好的解决方案。

我想到的解决方案也就是下面这些：
- 强制去掉路径中最后一个引号（反正引号不是合法路径字符）么？
- 命令行中不使用`"%dest%"`而是直接使用`%dest%`？（这样就不能支持任意目录拖过来的apk，有bug强迫症，感觉不爽）

**Comment by GavinCT** [comment]
```groovy
compile "com.beust:jcommander:1.66"
```
我们使用的是1.48版本，是否可以帮我们测试下最近发布的1.66版呢 ？ 看是否解决了这个问题

**Comment by k1988** [comment]
嗯，试了下1.66版本，并没有解决。

**Comment by GavinCT** [comment]
ok thanks 我们看看怎么处理下

**Comment by GavinCT** [comment]
脚本是否方便完全提供给我们呢？ windows下的脚本我不太熟。 想使用测试下。 隐私信息可以隐藏下，脚本能跑测试就好 麻烦了

**Comment by GavinCT** [comment]
或者都不方便的话 帮我们试下 Args4J or Commons-CLI 是否可以在这种case下正常工作呢？   
个人倾向于不针对具体case做补丁，如果解析框架能支持最好

**Comment by k1988** [comment]
、
不好意思，没有及时回复。
脚本就上面写的应用场景中的代码，测试用例：在某目录下放四个文件，test.bat、channel.txt、test.apk、walle-cli-all.jar。
然后test.bat里写入以下代码：
```
set src=%1%
set dest=%~dp1%
java -jar walle-cli-all.jar batch -f channel.txt  "%src%" "%dest%"
pause
```

然后打开cmd，cd到此目录，输入test.bat test.apk即可。

**Comment by GavinCT** [comment]
好的 十分感谢

**Comment by GavinCT** [comment]
试了一下，args4j也是同样的问题。
我们下版针对window平台移除下`"`吧 mac下`"`是合法字符 看了下linux也没有什么规定

**Comment by GavinCT** [comment]
1.1.3版本已经修复 @k1988
