### ISSUE TITLE
cli给APK写入渠道号失败No APK Signing Block before ZIP Central Directory

### ISSUE THREAD

**Issue by johnneywzd** [Meituan-Dianping/walle#113]
我使用cli来写入渠道号，按说很简单啊，一条指令就行了。但是为什么报错呢？需要对apk做什么预先操作么？

No APK Signing Block before ZIP Central Directory 这个如何解决？

java -jar walle-cli-all.jar put -c 001  myapp.apk 

com.meituan.android.walle.SignatureNotFoundException: No APK Signing Block before ZIP Central Directory
        at com.meituan.android.walle.ApkUtil.findApkSigningBlock(ApkUtil.java:125)
        at com.meituan.android.walle.PayloadWriter.handleApkSigningBlock(PayloadWriter.java:77)
        at com.meituan.android.walle.PayloadWriter.putAll(PayloadWriter.java:43)
        at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:31)
        at com.meituan.android.walle.ChannelWriter.putRaw(ChannelWriter.java:73)
        at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:55)
        at com.meituan.android.walle.commands.PutCommand.parse(PutCommand.java:51)
        at com.meituan.android.walle.Main.main(Main.java:51)

**Comment by GavinCT** [comment]
先签名再写渠道好。
