### ISSUE TITLE
SignatureNotFoundException

### ISSUE THREAD

**Issue by Suaix** [Meituan-Dianping/walle#115]
使用walle-cli命令行打包报SignatureNotFoundException，但是我已经对应用签名了，没有启动V2签名；以下是错误日志：
com.meituan.android.walle.SignatureNotFoundException: No APK Signing Block before ZIP Central Directory
	at com.meituan.android.walle.ApkUtil.findApkSigningBlock(ApkUtil.java:156)
	at com.meituan.android.walle.PayloadWriter.handleApkSigningBlock(PayloadWriter.java:73)
	at com.meituan.android.walle.PayloadWriter.putAll(PayloadWriter.java:43)
	at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:31)
	at com.meituan.android.walle.ChannelWriter.putRaw(ChannelWriter.java:73)
	at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:55)
	at com.meituan.android.walle.commands.BatchCommand.generateChannelApk(BatchCommand.java:81)
	at com.meituan.android.walle.commands.BatchCommand.parse(BatchCommand.java:51)
	at com.meituan.android.walle.Main.main(Main.java:51)

**Comment by GavinCT** [comment]
walle只对v2签名生效。 请注意看readme

**Comment by Suaix** [comment]
尴尬啦！readme里没看到，多谢解答！
