### ISSUE TITLE
重新签名后再修改渠道失败

### ISSUE THREAD

**Issue by MonchChen** [Meituan-Dianping/walle#15]
使用jarsigner对apk重新签名后，再执行写入渠道号失败，异常：
com.meituan.android.walle.SignatureNotFoundException: No APK Signing Block before ZIP Central Directory
	at com.meituan.android.walle.ApkUtil.findApkSigningBlock(ApkUtil.java:125)
	at com.meituan.android.walle.PayloadWriter.handleApkSigningBlock(PayloadWriter.java:77)
	at com.meituan.android.walle.PayloadWriter.putAll(PayloadWriter.java:43)
	at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:31)
	at com.meituan.android.walle.ChannelWriter.putRaw(ChannelWriter.java:73)
	at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:55)
	at com.meituan.android.walle.commands.WriteChannelCommand.parse(WriteChannelCommand.java:51)
	at com.meituan.android.walle.Main.main(Main.java:49)

**Comment by achellies** [comment]
jarsigner只能生成V1的签名，运行下apksigner verify 看看是不是V1的签名，如果想签名请使用apksigner来签V2的签名
