### ISSUE TITLE
使用腾讯应用宝乐固加固后，渠道号获取不到

### ISSUE THREAD

**Issue by tigerface** [Meituan-Dianping/walle#155]
使用腾讯应用宝乐固加固后，渠道号获取不到。
再使用以下命令单独打渠道号，报错。
java -jar walle-cli-all.jar put -c [渠道文件] [apk路径] [生成的新apk路径（可选）]
报错日志
com.meituan.android.walle.SignatureNotFoundException: No APK Signing Block before ZIP Central Directory
        at com.meituan.android.walle.ApkUtil.findApkSigningBlock(ApkUtil.java:156)
        at com.meituan.android.walle.PayloadWriter.handleApkSigningBlock(PayloadWriter.java:164)
        at com.meituan.android.walle.PayloadWriter.putAll(PayloadWriter.java:98)
        at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:75)
        at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:48)
        at com.meituan.android.walle.ChannelWriter.putRaw(ChannelWriter.java:101)
        at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:76)
        at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:49)
        at com.meituan.android.walle.commands.PutCommand.parse(PutCommand.java:51)
        at com.meituan.android.walle.Main.main(Main.java:51)

**Comment by GavinCT** [comment]
看样子是没有v2签名区。  可以看看有没有新版的应用宝加固方案。
也可以参考下360加固遇到的问题，解决方案应该类似
