### ISSUE TITLE
在签名加固包的时候报错.No APK Signing Block before ZIP Central Directory

### ISSUE THREAD

**Issue by lhalcyon** [Meituan-Dianping/walle#166]
如题,报错如下
com.meituan.android.walle.SignatureNotFoundException: No APK Signing Block before ZIP Central Directory
	at com.meituan.android.walle.ApkUtil.findApkSigningBlock(ApkUtil.java:156)
	at com.meituan.android.walle.PayloadWriter.handleApkSigningBlock(PayloadWriter.java:164)
	at com.meituan.android.walle.PayloadWriter.putAll(PayloadWriter.java:98)
	at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:75)
	at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:48)
	at com.meituan.android.walle.ChannelWriter.putRaw(ChannelWriter.java:101)
	at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:76)
	at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:49)
	at com.meituan.android.walle.commands.PutCommand.parse(PutCommand.java:51)
	at com.meituan.android.walle.Main.main(Main.java:51)

**Comment by lhalcyon** [comment]
不好意思,已解决.因为用加固工具直接签名的是用的Java签名方式,实际上通过walle签名应该用v2.
整个流程已经ok.用爱加密加固的也可用瓦力进行多渠道打包! 👌

**Comment by ponyfe** [comment]
> 不好意思,已解决.因为用加固工具直接签名的是用的Java签名方式,实际上通过walle签名应该用v2. 整个流程已经ok.用爱加密加固的也可用瓦力进行多渠道打包! 👌

补充一下：
jarsigner签名不是v2，用Google的apksigner就可以了
