### ISSUE TITLE
能打unity打出来的渠道包吗

### ISSUE THREAD

**Issue by huaminghui** [Meituan-Dianping/walle#175]
因为之前我是用这个做android打渠道包也很好用，但是我现在用Unity打android的包，然后在用walle-cli 命令去写入的时候报错了
com.meituan.android.walle.SignatureNotFoundException: No APK Signing Block before ZIP Central Directory
	at com.meituan.android.walle.ApkUtil.findApkSigningBlock(ApkUtil.java:156)
	at com.meituan.android.walle.PayloadWriter.handleApkSigningBlock(PayloadWriter.java:164)
	at com.meituan.android.walle.PayloadWriter.putAll(PayloadWriter.java:98)
	at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:75)
	at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:48)
	at com.meituan.android.walle.ChannelWriter.putRaw(ChannelWriter.java:101)
	at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:76)
	at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:49)
	at com.meituan.android.walle.commands.Batch2Command.generateChannelApk(Batch2Command.java:89)
	at com.meituan.android.walle.commands.Batch2Command.parse(Batch2Command.java:73)
	at com.meituan.android.walle.Main.main(Main.java:51)
我想问下，这个打包有什么要求吗？或者说这个能集成到unity中吗

**Comment by GavinCT** [comment]
可以 只要你确保自己打出来的apk是v2签名即可。

**Comment by GavinCT** [comment]
这种报错是因为你的apk包还是v1，不是v2签名导致的

**Comment by huaminghui** [comment]
我已经找到解决办法了，unity打包出来的是v1的，我又用360加固重新签名写入就ok了
