### ISSUE TITLE
使用腾讯乐固加固后不能加入渠道

### ISSUE THREAD

**Issue by yugu91** [Meituan-Dianping/walle#179]
报错信息，用android studio打包出来的是正常的，经过腾讯乐固就这样了
com.meituan.android.walle.SignatureNotFoundException: No APK Signing Block before ZIP Central Directory
	at com.meituan.android.walle.ApkUtil.findApkSigningBlock(ApkUtil.java:156)
	at com.meituan.android.walle.PayloadWriter.handleApkSigningBlock(PayloadWriter.java:164)
	at com.meituan.android.walle.PayloadWriter.putAll(PayloadWriter.java:98)
	at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:75)
	at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:48)
	at com.meituan.android.walle.ChannelWriter.putRaw(ChannelWriter.java:101)
	at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:76)
	at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:49)
	at com.meituan.android.walle.commands.PutCommand.parse(PutCommand.java:51)
	at com.meituan.android.walle.Main.main(Main.java:51)

**Comment by achellies** [comment]
腾讯乐固会破坏签名区，导致V2签名丢了

**Comment by achellies** [comment]
https://github.com/Meituan-Dianping/walle/wiki/360%E5%8A%A0%E5%9B%BA%E5%A4%B1%E6%95%88%EF%BC%9F

**Comment by scsfwgy** [comment]
+1
