### ISSUE TITLE
加固后失效

### ISSUE THREAD

**Issue by wlj190785060** [Meituan-Dianping/walle#21]
使用第三方加固后，需要重新签名的，所以这种多渠道打包方式失效了。只能使用常规的gradle配置多渠道，加固后再签名

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/issues/4 
先加固  后签名 然后用walle对这个签名后的apk进行多渠道打包试试

**Comment by wlj190785060** [comment]
com.meituan.android.walle.SignatureNotFoundException: No APK Signing Block before ZIP Central Directory
	at com.meituan.android.walle.ApkUtil.findApkSigningBlock(ApkUtil.java:125)
	at com.meituan.android.walle.PayloadWriter.handleApkSigningBlock(PayloadWriter.java:77)
	at com.meituan.android.walle.PayloadWriter.putAll(PayloadWriter.java:43)
	at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:31)
	at com.meituan.android.walle.ChannelWriter.putRaw(ChannelWriter.java:73)
	at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:55)
	at com.meituan.android.walle.commands.WriteChannelCommand.parse(WriteChannelCommand.java:51)
	at com.meituan.android.walle.Main.main(Main.java:49)
意思是第三方平台不是用的v2签名打包的吗

**Comment by wlj190785060** [comment]
xxx@xxx-Pro libs$ java -jar walle-cli-all.jar put -c meituan /Users/wanglinjie/Downloads/app-release-ppzhushou_unsign_signed.apk 
com.meituan.android.walle.SignatureNotFoundException: No APK Signing Block before ZIP Central Directory
	at com.meituan.android.walle.ApkUtil.findApkSigningBlock(ApkUtil.java:125)
	at com.meituan.android.walle.PayloadWriter.handleApkSigningBlock(PayloadWriter.java:77)
	at com.meituan.android.walle.PayloadWriter.putAll(PayloadWriter.java:43)
	at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:31)
	at com.meituan.android.walle.ChannelWriter.putRaw(ChannelWriter.java:73)
	at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:55)
	at com.meituan.android.walle.commands.WriteChannelCommand.parse(WriteChannelCommand.java:51)
	at com.meituan.android.walle.Main.main(Main.java:49)

**Comment by GavinCT** [comment]
不用360提供的签名工具呢？  使用buildtool下的apksigner试试

**Comment by wlj190785060** [comment]
这个用第三方加固必须要用该平台下的加固方式，像百度只能用百度加固， 我现在用的爱加密试的，是不是不支持7.0？

**Comment by GavinCT** [comment]
加固是  但签名不是啊  看https://github.com/Meituan-Dianping/walle/issues/4

**Comment by achellies** [comment]
#4

**Comment by GavinCT** [comment]
![image](https://cloud.githubusercontent.com/assets/4016698/22615771/04a30e5e-ead7-11e6-8df0-3ab9c28c9e38.png)
一个用户反馈的 给你参考下吧

**Comment by wswenyue** [comment]
可以试试这个，支持360渠道加固
https://github.com/wswenyue/channelHelper

**Comment by zengwenling** [comment]
@GavinCT  我用的360加固，没有签名不让加固啊
![image](https://cloud.githubusercontent.com/assets/6247675/25262200/fff5cfb6-2688-11e7-8878-769dfde79fb5.png)
可以先用签名的包加固，加固后再重新对齐，签名吗？

**Comment by NiLuogege** [comment]
对简单而且能有效解决问题的工具 https://github.com/NiLuogege/walleBuildChannel
