### ISSUE TITLE
在使用命令行打包的时候apk大小超过2G导致错误

### ISSUE THREAD

**Issue by BrysonFeng** [Meituan-Dianping/walle#374]
在使用命令行打包的时候apk大小超过2G导致错误，错误如下
PS C:\Users\Administrator\Desktop\my_jolo_work\V1V2兼容打包工具> java -jar walle-cli-all.jar put -c meituan unsign.apk
com.meituan.android.walle.SignatureNotFoundException: APK too small for APK Signing Block. ZIP Central Directory offset: -2147355221
        at com.meituan.android.walle.ApkUtil.findApkSigningBlock(ApkUtil.java:143)
        at com.meituan.android.walle.PayloadWriter.handleApkSigningBlock(PayloadWriter.java:164)
        at com.meituan.android.walle.PayloadWriter.putAll(PayloadWriter.java:98)
        at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:75)
        at com.meituan.android.walle.PayloadWriter.put(PayloadWriter.java:48)
        at com.meituan.android.walle.ChannelWriter.putRaw(ChannelWriter.java:101)
        at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:76)
        at com.meituan.android.walle.ChannelWriter.put(ChannelWriter.java:49)
        at com.meituan.android.walle.commands.PutCommand.parse(PutCommand.java:51)
        at com.meituan.android.walle.Main.main(Main.java:51)

**Comment by LBCross** [comment]
超过2GB的问题解决了吗？

**Comment by Bingoliallen** [comment]
用支持V1签名的apkcomment往apk（zip）的 file comment 区域添加自定义数据的方式打渠道包，详见：https://github.com/linghaolu/apkcomment
