### ISSUE TITLE
官方两年没更新了，fork了一个版本，已适配agp7.x，详见下面

### ISSUE THREAD

**Issue by Petterpx** [Meituan-Dianping/walle#377]
https://github.com/Petterpx/walle

**Comment by kuroyukihime0** [comment]
![image](https://user-images.githubusercontent.com/7975549/173002857-d8d8e79b-9016-43ec-9bbd-82ca2c31de71.png)
这个版本使用cli时报错，官方的没有问题

**Comment by Alexxiaopang** [comment]
> ![image](https://user-images.githubusercontent.com/7975549/173002857-d8d8e79b-9016-43ec-9bbd-82ca2c31de71.png) 这个版本使用cli时报错，官方的没有问题

请使用java11，java8会出现错误，语法不一样了

**Comment by timmy-gzw** [comment]
apkFileNameFormat 似乎无效.

**Comment by OneGreenHand** [comment]
@Petterpx 
https://github.com/Meituan-Dianping/walle/issues/351
请问你那个里面有没有加这个问题的解决方案进去，因为部分手机无法安装，谢谢

**Comment by Petterpx** [comment]
> 

ok,我稍等改一下，目前是没加的

**Comment by Petterpx** [comment]
> apkFileNameFormat 似乎无效.



> @Petterpx #351 请问你那个里面有没有加这个问题的解决方案进去，因为部分手机无法安装，谢谢

ok,我稍等改一下，目前是没加的

**Comment by OneGreenHand** [comment]
@Petterpx 辛苦大佬了

**Comment by Petterpx** [comment]
> apkFileNameFormat 似乎无效.

ok,我晚会看看

**Comment by Petterpx** [comment]
> @Petterpx #351 请问你那个里面有没有加这个问题的解决方案进去，因为部分手机无法安装，谢谢

这个问题里只是输出的渠道包增加了别名，关于部分手机无法安装，应该是属于编译的问题，这个这边测试没啥问题。

**Comment by yiranshaxiao** [comment]
Android Studio Dolphin | 2021.3.1
gradle jdk 11.0.13
com.android.tools.build:gradle:7.2.2
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip


https://github.com/Petterpx/walle/blob/main/plugin/src/main/groovy/com/meituan/android/walle/ChannelMaker.groovy#L262

Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.io.File(String, File)
        at com.meituan.android.walle.ChannelMaker.generateChannelApk(ChannelMaker.groovy:262)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at com.meituan.android.walle.ChannelMaker$_packaging_closure5.doCall(ChannelMaker.groovy:122)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at com.meituan.android.walle.ChannelMaker.packaging(ChannelMaker.groovy:121)

**Comment by gyxing** [comment]
> 

apkFileNameFormat  这个加好了没？

**Comment by Petterpx** [comment]
> > 
> 
> apkFileNameFormat 这个加好了没？

加好了，1.0.4即可

**Comment by cigk** [comment]
> apkFileNameFormat

1.0.4 版本 apkFileNameFormat设置了貌似也不生效

**Comment by maynezhou** [comment]
1.0.4 版本 apkFileNameFormat设置了貌似也不生效

**Comment by MayDayzll** [comment]
@Petterpx  哥有时间麻烦您升级下[walle](https://github.com/Petterpx/walle)8.多的项目

**Comment by Petterpx** [comment]
> 1.0.4 版本 apkFileNameFormat设置了貌似也不生效

试试1.0.5呢

**Comment by sy5251** [comment]
> > 1.0.4 版本 apkFileNameFormat设置了貌似也不生效
> 
> 试试1.0.5呢

1.0.5 在安卓9会报错

java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)
                                                                                                    	at com.meituan.android.walle.ApkUtil.sliceFromTo(ApkUtil.java:262)
                                                                                                    	at com.meituan.android.walle.ApkUtil.findIdValues(ApkUtil.java:202)
                                                                                                    	at com.meituan.android.walle.PayloadReader.getAll(PayloadReader.java:84)
                                                                                                    	at com.meituan.android.walle.PayloadReader.get(PayloadReader.java:44)
                                                                                                    	at com.meituan.android.walle.PayloadReader.getString(PayloadReader.java:24)
                                                                                                    	at com.meituan.android.walle.ChannelReader.getRaw(ChannelReader.java:67)
                                                                                                    	at com.meituan.android.walle.ChannelReader.getMap(ChannelReader.java:42)
                                                                                                    	at com.meituan.android.walle.ChannelReader.get(ChannelReader.java:25)
                                                                                                    	at com.meituan.android.walle.WalleChannelReader.getChannelInfo(WalleChannelReader.java:56)
                                                                                                    	at com.meituan.android.walle.WalleChannelReader.getChannel(WalleChannelReader.java:37)

**Comment by cgzwyy** [comment]
Could not apply requested plugin [id: 'com.github.Petterpx.walle', version: '1.0.5', artifact: 'com.github.Petterpx.walle:plugin:1.0.5'] as it does not provide a plugin with id 'com.github.Petterpx.walle'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).

**Comment by cgzwyy** [comment]
agp 8.5 这是什么原因
