### ISSUE TITLE
能否支持下agp 8?  Agp 8 报错如下

### ISSUE THREAD

**Issue by SheepYoung** [Meituan-Dianping/walle#383]
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.io.File(String, File)
        at org.gradle.internal.classpath.intercept.CallInterceptorsSet$DecoratingCallSite.access$401(CallInterceptorsSet.java:150)
        at org.gradle.internal.classpath.intercept.CallInterceptorsSet$DecoratingCallSite$4.callOriginal(CallInterceptorsSet.java:204)
        at org.gradle.internal.classpath.intercept.CallInterceptorsSet$1.doIntercept(CallInterceptorsSet.java:63)
        at org.gradle.internal.classpath.intercept.CallInterceptorsSet$DecoratingCallSite.callConstructor(CallInterceptorsSet.java:201)
        at com.meituan.android.walle.ChannelMaker.generateChannelApk(ChannelMaker.groovy:262)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.meituan.android.walle.ChannelMaker$_generateChannelApkByConfigFile_closure8.doCall$original(ChannelMaker.groovy:228)
        at com.meituan.android.walle.ChannelMaker$_generateChannelApkByConfigFile_closure8.doCall(ChannelMaker.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.meituan.android.walle.ChannelMaker.generateChannelApkByConfigFile(ChannelMaker.groovy:204)
        at com.meituan.android.walle.ChannelMaker$generateChannelApkByConfigFile$1.callCurrent(Unknown Source)
        at com.meituan.android.walle.ChannelMaker.packaging(ChannelMaker.groovy:154)

**Comment by nodzhang** [comment]
项目已经不维护了，估计不会适配gradle 8 了
