### ISSUE TITLE
walle 配置插件,生成的apk文件名可不可以自己定义啊？

### ISSUE THREAD

**Issue by ouyangpeng** [Meituan-Dianping/walle#77]
walle 配置插件,生成的apk文件名
```
walle {
    // 指定渠道包的输出路径
    apkOutputFolder = new File("${project.buildDir}/outputs/channels");
    // 定制渠道包的APK的文件名称
    apkFileNameFormat = '${appName}-${packageName}-${channel}-${buildType}-v${versionName}-${versionCode}-${buildTime}.apk';
    // 渠道配置文件
    channelFile = new File("${project.getProjectDir()}/channel")
}
```

配置项具体解释：
```
    apkOutputFolder：指定渠道包的输出路径， 默认值为new File("${project.buildDir}/outputs/apk")

    apkFileNameFormat：定制渠道包的APK的文件名称, 默认值为'${appName}-${buildType}-${channel}.apk'
    可使用以下变量:

        projectName - 项目名字
        appName - App模块名字
        packageName - applicationId (App包名packageName)
        buildType - buildType (release/debug等)
        channel - channel名称 (对应渠道打包中的渠道名字)
        versionName - versionName (显示用的版本号)
        versionCode - versionCode (内部版本号)
        buildTime - buildTime (编译构建日期时间)
        fileSHA1 - fileSHA1 (最终APK文件的SHA1哈希值)
        flavorName - 编译构建 productFlavors 名

    channelFile：包含渠道配置信息的文件路径。 具体内容格式详见：渠道配置文件示例，支持使用#号添加注释。
```

我想在apk文件名加上 svn版本号和Jenkins编译出来的版本号，之前我们在build.gralde文件中定义了相应的方法来获取svn版本号和Jenkins编译出来的版本号，getSvnRevisionByPlatform()，getJenkinsBuildCode() 。

```
//apkFileNameFormat = '${appName}-${packageName}-${channel}-${buildType}-v${versionName}-${versionCode}-${buildTime}.apk';
    apkFileNameFormat = "XTCWatch_"+v${versionName}+"_Release_"+${getSvnRevisionByPlatform()}+"_"+${getJenkinsBuildCode()}+"_"+${channel}+".apk";
```

但是我加入的之后，编译不了，会报错，错误如下：
```
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.xiaomi.smack.util.d) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method v$() for arguments [build_4ara8gl4zbswi60yx8e29m2r5$_run_c
losure4$_closure22@2d36add1] on project ':watch' of type org.gradle.api.Project.
        at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:182)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:167)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
        at build_4ara8gl4zbswi60yx8e29m2r5$_run_closure4.doCall(C:\Code\App_MultiChannelBigData\watch\build.gradle:307)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
        at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:215)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
        at build_4ara8gl4zbswi60yx8e29m2r5.run(C:\Code\App_MultiChannelBigData\watch\build.gradle:302)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
        ... 50 more


BUILD FAILED
```

是因为这样的格式不对劲吗？ 怎么写才是规范的格式来重命名要生成的apk名

**Comment by sylviaMo** [comment]
可以自定义啊，我是自定义成功的

**Comment by ouyangpeng** [comment]
@sylviaMo 应该是我自己写错格式了。

**Comment by achellies** [comment]
apkFileNameFormat = "XTCWatch_"+v${versionName}+"_Release_"+${getSvnRevisionByPlatform()}+"_"+${getJenkinsBuildCode()}+"_"+${channel}+".apk"; ===>
apkFileNameFormat = 'XTCWatch_v${versionName}_Release_${channel}.apk';

目前不支持在apkFileNameFormat中增加函数调用

**Comment by ouyangpeng** [comment]
@achellies 知道了，不支持在apkFileNameFormat中增加函数调用，目前采取的方式是  在 versionName 定义的时候，直接加入获取svn和jenkins的函数
``` versionName "3.5.0" + "." + getJenkinsName() + "_" + getJenkinsBuildCode()```
然后再walle配置的时候，使用
``` apkFileNameFormat = ' XTCWatch_'+'v${versionName}_${buildType}_${versionCode}_${channel}.apk'; ```
这样也会将jenkins和svn的相关信息，存到apk的名字中。

**Comment by achellies** [comment]
👍，好机智
